parser: typescript-eslint-parser
env:
  "browser": true,
  "es6": true,
  "node": true,
  "mocha": true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  indent:
  - error
  - 4
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - double
  semi:
  - error
  - always